name: github-pages
# inspired by https://blog.oldweb2.com/remix-static-site

on:
  push:
    branches: [main]
  #schedule:
  #  - cron: "42 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - run: go install golang.org/x/tools/cmd/present

      - name: start server and mirror it with wget
        run:
          go run golang.org/x/tools/cmd/present -http 0.0.0.0:3999 &
          sleep 5
          wget --mirror http://localhost:3999 -P out --no-host-directories --page-requisites --adjust-extension

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
