name: "table lint"

on:
  push:
    paths:
      - main
  pull_request:
    paths:
      - "presentations/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run linter
        run: make lint
